# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  # Expose port 80 on guest vis port 8080 on host
  config.vm.network "forwarded_port", guest: 4000, host: 4000, host_ip: "127.0.0.1"

  # Set guest IP address on host network
  config.vm.network "private_network", ip: "192.168.10.101"

  # Additional folders to sync between host and guest
  config.vm.synced_folder "D:\\Development\\Projects\\DTF", "/home/vagrant/DTF"

  # Config VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = 'bionic-dev'
    vb.memory = 4096
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  
  # Upgrade, install git and the CircleCI CLI
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt full-upgrade -y
    apt-get install -y git
    curl -fLSs https://circle.ci/cli | bash
  SHELL
  
  # Install Docker
  config.vm.provision :docker
end